### ISSUE TITLE
Run tests on the same device even caps are different, if the port of WDA on each device is the same

### ISSUE THREAD

**Issue by KazuCocoa** [NozomiIto/AppiumRegressionCheck#1]
- Summary: https://github.com/KazuCocoa/AppiumRegressionCheck/issues/2#issue-306161336
- Result: https://github.com/KazuCocoa/AppiumRegressionCheck/issues/2#issuecomment-37

cc @NozomiIto

**Comment by NozomiIto** [comment]
Now all test worked for the first time. Thanks for your good advice!!

- I resolved the mixed WDA communication problem for multiple iOS devices by using the different port for each device. Currently I don't use useNewWDA because it does not work on the real device and can make the test slower even on the simulator.
- Also, the test code has become very simple, since killing simulator and using fullReset are now unnecessary.
